name: Backend API CI - Build and Push Docker Image

on:
  push:
    branches:
      - main # Se dispara en pushes a la rama main
    paths:
      - 'backend-api/**' # Solo si hay cambios dentro de la carpeta backend-api
  workflow_dispatch: # Permite ejecutarlo manualmente desde la UI de GitHub

jobs:
  build-and-push-docker-image:
    name: Build and Push API Docker Image
    runs-on: ubuntu-latest # Usaremos un runner de GitHub con Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: robleslf/opadi-api # Reemplaza con TU_USUARIO_DOCKERHUB/opadi-api

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend-api # El contexto es el directorio de la API
          file: ./backend-api/Dockerfile # Ruta al Dockerfile de la API
          push: true # SÃ­ queremos hacer push a Docker Hub
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
